[[redirects]]
  from = "/"
  to = "/main.html"
  status = 404
  force = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "en/*"
  to = "en/404.html"
  status = 404
  force = true
